# Generated by Django 6.1 on 2026-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_movie_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(null=True, upload_to="movie_posters/"),
        ),
    ]
