# Generated by Django 6.1 on 2026-08-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_movie_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="cinemahall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="core.cinemahall",
            ),
        ),
    ]
