# Generated by Django 6.1 on 2026-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_reservation_customer_alter_reservation_seat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pd", "Pending"),
                    ("cm", "Confirmed"),
                    ("cl", "Cancelled"),
                    ("ex", "Expired"),
                ],
                default="pd",
                max_length=2,
            ),
        ),
    ]
