# Generated by Django 6.1 on 2026-09-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_reservation_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("name", "cinemahall")},
        ),
    ]
