# Generated by Django 6.0.8 on 2026-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_seat_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
