# Generated by Django 6.0.8 on 2026-09-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_reservation_created_at_reservation_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="master_reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="core.masterreservation",
            ),
        ),
    ]
