# Generated by Django 6.0.8 on 2026-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_masterreservation_reservation_master_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterreservation",
            name="pidx",
            field=models.CharField(
                default="", help_text="Payment intiate id from khalti", max_length=60
            ),
        ),
    ]
