# Generated by Django 6.0.8 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_masterreservation_pidx"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterreservation",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="masterreservation",
            name="payment_status",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="masterreservation",
            name="transaction_id",
            field=models.CharField(default="", max_length=60),
        ),
    ]
