# Generated by Django 6.0.8 on 2026-09-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_masterreservation_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterreservation",
            name="show",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="master_reservations",
                to="core.show",
            ),
        ),
    ]
