# Generated by Django 6.0.8 on 2026-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_masterreservation_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterreservation",
            name="payment_status",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="masterreservation",
            name="pidx",
            field=models.CharField(
                help_text="Payment intiate id from khalti", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="masterreservation",
            name="transaction_id",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
