# Generated by Django 6.0.8 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_masterreservation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="col",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cinemahall",
            name="row",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
