# Generated by Django 6.0.8 on 2026-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cinemahall_col_cinemahall_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="col",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cinemahall",
            name="row",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
