# Generated by Django 6.0.8 on 2026-09-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_cinemahall_col_alter_cinemahall_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="halls",
                to="core.cinema",
            ),
        ),
    ]
