# Generated by Django 6.0.8 on 2026-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(null=True, upload_to="profile_photos/"),
        ),
    ]
